# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  node: 
    steps:
      - run: 
          name: install dependencies
          command: yarn

      - save_cache:
          key: deps-envoy-{{ checksum "yarn.lock" }}
          paths:
            - 'node_modules'

      - run:
          name: build dependencies
          command: yarn build
          
workflows: 
  version: 2.1
  build-deploy: 
    jobs: 
      - node
