# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'

jobs: 
  install:
    steps: 
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          key: deps-envoy-{{ checksum "yarn.lock" }}
          paths:
            - 'node_modules'

  build-dependencies:
    steps:
      - run: 
          name: build dependencies
          command: yarn build

    
# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  build-project: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - install
      - build-dependencies
          

        
    
